# Generated by Django 4.2.9 on 2026-04-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('author', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('biography', 'Biography'), ('self-help', 'Self-Help'), ('business', 'Business'), ('history', 'History'), ('science', 'Science'), ('technology', 'Technology'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('num_ratings', models.IntegerField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('book_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, help_text='Source website', max_length=100, null=True)),
                ('content_text', models.TextField(blank=True, help_text='Full text content for RAG', null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI-generated insights')),
                ('embedding_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('goodreads', 'Goodreads'), ('amazon', 'Amazon'), ('openlibrary', 'Open Library'), ('custom', 'Custom URL')], max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('books_scraped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scraping_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='books.book')),
            ],
            options={
                'db_table': 'qa_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.book')),
            ],
            options={
                'db_table': 'favorite_books',
            },
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('recommendation_type', models.CharField(default='similar', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_from', to='books.book')),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to='books.book')),
            ],
            options={
                'db_table': 'book_recommendations',
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding_id', models.CharField(db_index=True, max_length=100)),
                ('chunk_type', models.CharField(default='text', help_text='chapter, paragraph, section, etc.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'db_table': 'book_chunks',
                'ordering': ['book', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='books_title_e8b1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-rating'], name='books_rating_a3b323_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_created_9e859d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('book',)},
        ),
        migrations.AlterUniqueTogether(
            name='bookrecommendation',
            unique_together={('source_book', 'recommended_book')},
        ),
        migrations.AlterUniqueTogether(
            name='bookchunk',
            unique_together={('book', 'chunk_index')},
        ),
    ]
